blog/web/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class BlogPostForm(FlaskForm):

    title = StringField('Title: ', validators=[DataRequired()])
    description = TextAreaField('Description: ', validators=[DataRequired()])
    submit = SubmitField('Post')

blog/web/__init__.py
from .. import app, login_manager
from .posts.views import posts
from .auth.views import auth
from .core.views import core
from .error.handler import error


def init_web_app():

    app.template_folder = 'web/templates'
    app.static_folder = 'web/static'

    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    app.register_blueprint(core)
    app.register_blueprint(error)
    app.register_blueprint(auth, url_prefix='/auth')
    app.register_blueprint(posts, url_prefix='/posts')

blog/web/core/views.py
from flask import Blueprint, render_template, request

from ...models import Post

core = Blueprint('core', __name__)

@core.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.datetime.desc()).paginate(page=page, per_page=5)

    return render_template('home.html', posts=posts)


@core.route('/info')
def info():
    return render_template('info.html')

blog/web/posts/views.py
from flask import (
    Blueprint, render_template, request, url_for, redirect, flash, abort
)
from flask_login import current_user, login_required
from ... import db
from ...models import User, Post
from .forms import BlogPostForm

posts = Blueprint('posts', __name__)


@posts.route('/user_posts/<username>')
def user_posts(username):

    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=user).order_by(
        Post.datetime.desc()).paginate(page=page, per_page=5)

    return render_template('user-blog-posts.html', user=user, posts=posts)


@posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):

    post = Post.query.get_or_404(blog_post_id)

    return render_template('blog-post.html', post=post)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():

    form = BlogPostForm()

    if form.validate_on_submit():

        new_post = Post(
            title=form.title.data,
            desc=form.description.data,
            author_id=current_user.id
        )
        db.session.add(new_post)
        db.session.commit()
        flash('New post has been created')

        return redirect(url_for('core.home'))

    return render_template('create-post.html', form=form)


@posts.route('/<int:blog_post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(blog_post_id):

    post = Post.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        post.title = form.title.data
        post.desc = form.description.data
        db.session.commit()
        flash('Post has been updated')

        return redirect(url_for('posts.blog_post', blog_post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.description.data = post.desc

    return render_template('update-post.html', form=form)


@posts.route('/<int:blog_post_id>/delete')
@login_required
def delete_post(blog_post_id):

    post = Post.query.get_or_404(blog_post_id)

    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted')

    return redirect(url_for('core.home'))

blog/web/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company Blog Flask</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <style>
        body {
            padding-top: 55px
        }
    </style>
</head>

<body>
    <nav class="navbar fixed-top bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('core.home') }}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('core.info') }}">About Us</a>
                    </li>
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.profile') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('posts.create_post') }}">Create Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% for msg in get_flashed_messages() %}
    <div class="alert alert-success alert-dismissible fade show mx-2 mt-2 fs-6 fw-semibold" role="alert">
        {{ msg }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}

    {% block content %}
    {% endblock %}
</body>

</html>

blog/web/templates/blog-post.html
{% extends "base.html" %}

{% block content %}
<div class="container bg-body-tertiary rounded-3 p-5 my-5 lh-1">
    <h1 class="fs-1 fw-semibold">{{ post.title }}</h1>
    <p>Created By:
        <a class="link-underline link-underline-opacity-0"
            href="{{ url_for('posts.user_posts', username=post.author.username) }}">
            {{ post.author.username }}
        </a>
    </p>
    <p>Created On: {{ post.datetime.strftime('%Y-%m-%d') }}</p>
    <br />
    <p class="lh-base">{{ post.desc }}</p>
    <br />

    {% if post.author == current_user %}
    <a href="{{ url_for('posts.update_post', blog_post_id=post.id) }}" class="btn btn-primary">
        Update
    </a>
    <button type="button" class="btn btn-danger ms-3" data-bs-toggle="modal" data-bs-target="#deletePostModal">
        Delete Post
    </button>
    <div class="modal fade" id="deletePostModal" tabindex="-1" aria-labelledby="deletePostModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Delete Post</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this post?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', blog_post_id=post.id) }}">
                        <input type="submit" class="btn btn-danger" value="Confirm" />
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

blog/web/templates/create-post.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid my-5 text-center">
    <div class="col-md-6 mx-auto p-5 bg-body-tertiary rounded-3">
        <h1 class="fs-2 fw-semibold mb-4">Create Post</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.title.label }}</label>
                {{ form.title(class='form-control') }}
            </div>
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.description.label }}</label>
                {{ form.description(class='form-control', rows='5') }}
            </div>
            {{ form.submit(class='btn btn-primary text-center w-50 py-2') }}
        </form>
    </div>
</div>
{% endblock %}

blog/web/templates/error-pages/error-403.html
{% extends "base.html" %}

{% block content %}
<div class="container bg-body-tertiary text-center rounded-3 p-5 my-5">
    <h1 class="fs-1 fw-bold">403! Access Forbidden!</h1>
</div>
{% endblock %}

blog/web/templates/error-pages/error-404.html
{% extends "base.html" %}

{% block content %}
<div class="container bg-body-tertiary text-center rounded-3 p-5 my-5">
    <h1 class="fs-1 fw-bold">404! Page Not Found!</h1>
</div>
{% endblock %}

blog/web/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="bg-body-tertiary rounded-3 my-3 p-5">
        <h1 class="fs-1 fw-bolder">Hello! Welcome to this blog.</h1>
    </div>
</div>

<div class="container-fluid text-center mt-5">
    {% for post in posts.items %}
    <div class="col-md-8 mx-auto bg-body-tertiary rounded-3 p-5 my-4 text-start lh-1">
        <a class="link-underline link-underline-opacity-0"
            href="{{ url_for('posts.blog_post', blog_post_id=post.id) }}">
            <h2 class="fs-2 fw-semibold">{{ post.title }}</h2>
        </a>
        <p>Published by:
            <a class="link-underline link-underline-opacity-0"
                href="{{ url_for('posts.user_posts', username=post.author.username) }}">
                {{post.author.username}}
            </a>
        </p>
        <p>Published on: {{ post.datetime.strftime('%Y-%m-%d') }}</p>
        <br />
        <a href="{{ url_for('posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary" style="width: 200px;">
            Read Post
        </a>
    </div>
    {% endfor %}

    <nav class="my-5" aria-label="Blog post navigation">
        <ul class="pagination justify-content-center">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if posts.page == page_num %}
            <li class="page-item disabled"><a class="page-link" href="">{{ page_num }}</a></li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('core.home', page=page_num) }}">
                    {{ page_num }}
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}

blog/web/templates/info.html
{% extends "base.html" %}

{% block content %}
<div class="container my-5">
    <div class="p-5 text-center bg-body-tertiary rounded-3">
        <h1 class="text-body-emphasis fw-bold">About Us</h1>
        <p style="font-size:17px">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut volutpat consequat enim at mollis. Vivamus ut
            tellus
            sollicitudin, viverra risus ac, rutrum orci. Nunc ac nisi eleifend, facilisis mauris et, semper neque. Sed
            et
            sem eu turpis congue eleifend. Donec at lectus urna. Pellentesque sit amet odio tortor. In pulvinar lobortis
            libero quis efficitur. Nam consequat sodales orci, convallis ullamcorper nunc luctus id. Duis egestas ante
            quis
            gravida scelerisque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
            Praesent commodo, dolor vel gravida mollis, nisi turpis faucibus leo, molestie tempor nunc ligula non eros.
            Etiam lacus libero, euismod non porttitor id, egestas in eros. In dignissim libero sed tortor imperdiet
            feugiat.
            Nullam venenatis vehicula urna. Sed sagittis, dui id mollis pellentesque, eros velit mattis libero, ac
            malesuada
            libero elit vel libero.
        </p>
    </div>
</div>
{% endblock %}

blog/web/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid text-center my-5">
    <div class="col-md-4 p-5 bg-body-tertiary rounded-3 mx-auto text-start">
        <h1 class="fs-2 fw-semibold mb-4">Please Log In</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                <label class="form-label">{{ form.email.label }}</label>
                {{ form.email(class='form-control') }}
            </div>
            <div class="mb-4">
                <label class="form-label">{{ form.password.label }}</label>
                {{ form.password(class='form-control') }}
            </div>
            {{ form.submit(class='btn btn-primary w-100 py-2') }}
        </form>
    </div>
</div>
{% endblock %}

blog/web/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid text-center my-5">
    <div class="col-md-6 bg-body-tertiary rounded-3 p-5 mx-auto">
        <h1 class="fs-1 fw-bold mb-3">Welcome {{ current_user.username }}</h1>
        <img style="border-radius: 50%;" src="{{ profile_img }}" height="150" width="150" alt="profile_img" />
        <form method="POST" enctype="multipart/form-data" class="mt-3">
            {{ form.hidden_tag() }}
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.username.label }}</label>
                {{ form.username(class='form-control') }}
            </div>
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.email.label }}</label>
                {{ form.email(class='form-control') }}
            </div>
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.profile_img.label }}</label>
                {{ form.profile_img(class='form-control') }}
            </div>
            {{ form.submit(class='btn btn-primary text-center w-50 py-2') }}
        </form>
    </div>
</div>
{% endblock %}

blog/web/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid text-center my-5">
    <div class="col-md-4 p-5 bg-body-tertiary rounded-3 mx-auto text-start">
        <h1 class="fs-2 fw-semibold mb-4">Register New Account</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                <label class="form-label">{{ form.username.label }}</label>
                {{ form.username(class='form-control') }}
            </div>
            <div class="mb-3">
                <label class="form-label">{{ form.email.label }}</label>
                {{ form.email(class='form-control') }}
            </div>
            <div class="mb-3">
                <label class="form-label">{{ form.password.label }}</label>
                {{ form.password(class='form-control') }}
            </div>
            <div class="mb-4">
                <label class="form-label">{{ form.pass_confirm.label }}</label>
                {{ form.pass_confirm(class='form-control') }}
            </div>
            {{ form.submit(class='btn btn-primary w-100 py-2') }}
        </form>
    </div>
</div>
{% endblock %}

blog/web/templates/update-post.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid my-5 text-center">
    <div class="col-md-6 mx-auto p-5 bg-body-tertiary rounded-3">
        <h1 class="fs-2 fw-semibold mb-4">Update Post</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.title.label }}</label>
                {{ form.title(class='form-control') }}
            </div>
            <div class="mb-3 text-start">
                <label class="form-label">{{ form.description.label }}</label>
                {{ form.description(class='form-control', rows='5') }}
            </div>
            {{ form.submit(class='btn btn-primary text-center w-50 py-2') }}
        </form>
    </div>
</div>
{% endblock %}

blog/web/templates/user-blog-posts.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="my-5 text-center">
        <div class="col-md-8 mx-auto p-4 bg-body-tertiary rounded-3 lh-1">
            <h1 class="fs-2 fw-semibold">{{ user.username }}</h1>
            <p class="fs-6 fw-semibold mb-4">{{ user.email }}</p>
            <img style="border-radius: 50%;" height="120"
                src="{{ url_for('static', filename='profile_imgs/' + user.profile_img) }}" alt="profile_img" />
        </div>
    </div>

    {% for post in posts.items %}
    <div class="col-md-8 mx-auto bg-body-tertiary rounded-3 p-5 my-4 text-start lh-1">
        <a class="link-underline link-underline-opacity-0"
            href="{{ url_for('posts.blog_post', blog_post_id=post.id) }}">
            <h2 class="fs-2 fw-semibold">{{ post.title }}</h2>
        </a>
        <p>Published by:
            <a class="link-underline link-underline-opacity-0"
                href="{{ url_for('posts.user_posts', username=post.author.username) }}">
                {{post.author.username}}
            </a>
        </p>
        <p>Published on: {{ post.datetime.strftime('%Y-%m-%d') }}</p>
        <br />
        <a href="{{ url_for('posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary" style="width: 200px;">
            Read Post
        </a>
    </div>
    {% endfor %}

    <nav class="my-5" aria-label="User blog post navigation">
        <ul class="pagination justify-content-center">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if posts.page == page_num %}
            <li class="page-item disabled"> <a class="page-link">{{ page_num }}</a> </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="{{ url_for('posts.user_posts', username=user.username, page=page_num) }}">
                    {{ page_num }}
                </a>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}